name: bookstack-import-export-test-instance2

volumes:
  bookstack-db-data:
  bookstack-app-data:

services:
  db:
    image: mysql:8
    restart: unless-stopped
    networks:
      default:
        aliases:
          - bookstack-db-container
    ports:
      - "8820:3306"
    volumes:
      - type: volume
        source: bookstack-db-data
        target: /var/lib/mysql
    healthcheck:
      test: mysqladmin ping --host=localhost --user=$${MYSQL_USER} || exit 1
      start_period: 180s
      start_interval: 5s
      timeout: 5s
      interval: 300s
      retries: 3
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=bookstack_rootpass
      - MYSQL_DATABASE=bookstack_store
      - MYSQL_USER=bookstack_user
      - MYSQL_PASSWORD=bookstack_pass

  app:
    image: lscr.io/linuxserver/bookstack:version-v25.05.2
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      default:
        aliases:
          - bookstack-app-container
    ports:
      - "8821:80"
    healthcheck:
      test: curl -f -s http://localhost:80 || exit 1
      start_period: 300s
      start_interval: 3s
      timeout: 5s
      interval: 300s
      retries: 3
    volumes:
      - type: volume
        source: bookstack-app-data
        target: /config
    environment:
      - TZ=Asia/Tokyo
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:8821
      - APP_KEY=base64:Fp1wYbP9I8IQxZVbXpSDqCVOV8GfsvfjhoqTp4Nc1k8=
      - DB_HOST=bookstack-db-container
      - DB_PORT=3306
      - DB_DATABASE=bookstack_store
      - DB_USERNAME=bookstack_user
      - DB_PASSWORD=bookstack_pass
      - API_REQUESTS_PER_MIN=180
